export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const CUSTOMER_DELETED = "CUSTOMER_DELETED";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";
export const CUSTOMER_CREATED = "CUSTOMER_CREATED";
