export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const CUSTOMER_DELETED = "CUSTOMER_DELETED";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";
export const CUSTOMER_CREATED = "CUSTOMER_CREATED";
export const LOAD_CUSTOMER = "LOAD_CUSTOMER";
export const LOAD_ERROR = "LOAD_ERROR";
export const CUSTOMER_UPDATED = "CUSTOMER_UPDATED";
export const EDIT_CUSTOMER_FAILURE = "EDIT_CUSTOMER_FAILURE";
